query ($cursor: String) {
  user(login: "Sliam123456") {
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100, after: $cursor) {
      nodes {
        languages(first: 100) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}